### ISSUE TITLE
Adding images to the Rss 

### ISSUE THREAD

**Issue by ziadba95** [abjerner/Skybrud.Umbraco.RssUtils#1]
Hello, 
Thanks for the nice package which worked with me easily on umbraco 8, but I was wondering if it's possible to add an image to each rss item so it can be displayed when using an rss reader?

**Comment by abjerner** [comment]
Hi @ziadba95 

Images are not something that is directly supported by the RSS specification. But I think most RSS readers support HTML (eg. `<img />`) within the values of either the `RssItem.Description` property or `RssItem.Content` property.

Hope that helps ;)
